vendor openresty image
astronomer/ap-vendor pull request #175
Opened 2021-11-23 17:52 UTC by pgvishnuram

## Which issue this PR fixes

We are implementing a new feature to utilise external elastic logging and we are using openresty image , in order to manage and maintain we are vendoring to astronomer for quicker CVE fixes

## Summary of changes

openresty image Dockerfile

## Images are updated by this PR

- [ ] alertmanager
- [ ] blackbox-exporter
- [ ] configmap-reloader
- [ ] curator
- [ ] elasticsearch
- [ ] elasticsearch-exporter
- [ ] fluentd
- [ ] grafana
- [ ] keda
- [ ] keda-metrics-apiserver
- [ ] kibana
- [ ] kube-state
- [ ] kubed
- [ ] nats-server
- [ ] nats-streaming
- [ ] nats-exporter
- [ ] nginx
- [ ] nginx-es
- [ ] node-exporter
- [ ] pgbouncer
- [ ] pgbouncer-exporter
- [ ] postgresql
- [ ] postgres-exporter
- [ ] prometheus
- [ ] redis
- [ ] registry
- [ ] statsd-exporter

## Checklist

Place an '[x]' (no spaces) in all applicable fields. Please remove unrelated fields.

- [X] version.txt is updated in the changed image(s)

If a security scan fails for an unchanged image...

- [ ] a fix has been applied OR...
- [X] an [issue]() has been created

https://github.com/astronomer/issues/issues/3815
If adding a new image:

- [X] the directory has the same name you intend it to be published as, less a preceding "ap-"
- [X] the directory includes a file "version.txt", with version matching the underlying software version
- [X] the directory includes a file "cve-whitelist.yaml", which may be empty
- [X] the file .github/PULL_REQUEST_TEMPLATE.md is updated to include the image in the checklist
- [X] execute the script .circleci/generate_circleci_config.py, commit changes to .circleci/config.yml

## Additional notes for your reviewer

2021-11-24 05:26 UTC, pgvishnuram commented
@danielhoherd - can this be approved

2021-11-24 14:46 UTC, danielhoherd commented
@pgvishnuram cve-whitelist is no longer used and should be deleted. Also the list in the PR template needs to be sorted.

2021-11-24 15:19 UTC, pgvishnuram commented
@danielhoherd - merged master changes which sync's PR template and removed cve-whitelist.yaml file .

2021-11-24 15:55 UTC, danielhoherd requested changes

2021-11-25 00:23 UTC, danielhoherd approved these changes

2021-11-25 00:26 UTC, merged