Make it possible to override the UID/GID/username of the user running
astronomer/ap-vendor pull request #441
Opened 2022-11-10 09:53 UTC by andriisoldatenko

resolves https://github.com/astronomer/airflow-operator/issues/1161

Example:
```
docker build --build-arg UID=1001 --build-arg GID=1001 -t tt .
[+] Building 1.3s (9/9) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                       0.0s
 => => transferring dockerfile: 37B                                                                                                                                                                                                                        0.0s
 => [internal] load .dockerignore                                                                                                                                                                                                                          0.0s
 => => transferring context: 2B                                                                                                                                                                                                                            0.0s
 => [internal] load metadata for docker.io/library/redis:6.2.7                                                                                                                                                                                             0.0s
 => [1/5] FROM docker.io/library/redis:6.2.7                                                                                                                                                                                                               0.0s
 => CACHED [2/5] RUN apt-get update &&     apt-get dist-upgrade -y &&     rm -rf /var/lib/apt/lists/*                                                                                                                                                      0.0s
 => [3/5] RUN groupmod -g 1001 redis   && chgrp 1001 /data                                                                                                                                                                                                 0.2s
 => [4/5] RUN usermod -u 1001 -g 1001 redis                                                                                                                                                                                                                0.4s
 => [5/5] RUN chown -R 1001:1001 /usr/local/bin/redis*                                                                                                                                                                                                     0.4s
 => exporting to image                                                                                                                                                                                                                                     0.1s
 => => exporting layers                                                                                                                                                                                                                                    0.1s
 => => writing image sha256:809ae6cfe235507b6268168e0a9191ccca407d64e618d2097cc32fe8dec622f9                                                                                                                                                               0.0s
 => => naming to docker.io/library/tt                                                                              
```

```
$ docker run -it tt sh
$ id
uid=1001(redis) gid=1001(redis) groups=1001(redis)
$
```

2022-11-10 10:11 UTC, ashb approved these changes

2022-11-10 10:19 UTC, andriisoldatenko commented on redis/Dockerfile
> +USER $UNAME
```suggestion
USER $UID:$GID
```
@pgvishnuram do you mean this?

2022-11-10 10:35 UTC, pgvishnuram commented on redis/Dockerfile
> +USER $UNAME
```USER $UNAME -> USER $UID ```

2022-11-10 19:12 UTC, danielhoherd commented on redis/Dockerfile
> +ENV UNAME=redis
Given that `uname` is something different, and `$USER` is already used to hold the username, I think we should do this:

```suggestion
ENV USER=redis
```

2022-11-10 19:13 UTC, danielhoherd commented on redis/Dockerfile
> +ENV UNAME=redis
Or do we even need this ENV var to hold the username, since it will always be "redis"?

2022-11-18 19:39 UTC, andriisoldatenko commented
@danielhoherd PTAL

2022-11-18 19:45 UTC, danielhoherd approved these changes
I still really dislike the variable `UNAME` being used to indicate the user name, and think we should use `USER` or `USERNAME`. Other than that, this all looks good.

EDIT: just to add some reasoning, `ENV` vars in Dockerfiles persist to the runtime environment. a `UNAME` var may be misinterpreted by something that expects that to contain `uname` style info. Really low chance of this happening, but it's better to err on the side of caution when it's so easy to select a more canonical variable name for storing the user name.

2022-11-18 19:52 UTC, andriisoldatenko commented
> I still really dislike the variable `UNAME` being used to indicate the user name, and think we should use `USER` or `USERNAME`. Other than that, this all looks good.

yeah i can fix it, one moment.

2022-12-06 21:09 UTC, danielhoherd approved these changes
LGTM

2022-12-06 21:10 UTC, danielhoherd requested changes
@andriisoldatenko We'll need to bump the version.txt in all of these dirs to successfully build and ship the new versions to the docker repos.

2022-12-07 19:07 UTC, andriisoldatenko commented
> @andriisoldatenko We'll need to bump the version.txt in all of these dirs to successfully build and ship the new versions to the docker repos.

@danielhoherd done!.

2022-12-07 19:13 UTC, danielhoherd commented on redis/version.txt
> +6.2.8
Because we're still using `FROM redis:6.2.7`:
```suggestion
6.2.7-1
```

2022-12-07 19:45 UTC, danielhoherd approved these changes

2022-12-07 19:57 UTC, danielhoherd approved these changes

2022-12-07 21:00 UTC, danielhoherd approved these changes

2022-12-07 21:08 UTC, merged