add prisma scan
astronomer/ap-vendor pull request #605
Opened 2023-09-25 15:29 UTC by pgvishnuram

## Details

Do not merge this PR until this description is replaced with relevant info about what images are being updated and what changes are being made.

## Related Issues

Do not merge this PR until this text is replaced with links to related issues if one exists, or else this section is deleted.

## Checklist

- [ ] version.txt was updated

2023-09-25 16:09 UTC, danielhoherd commented on .circleci/continue-config.yml.j2
> +            ./twistcli images scan --address $CONSOLE_URL --user=$USER --password=$PASSWORD --details ap-"<< parameters.directory >>":${CIRCLE_SHA1}
```suggestion
            ./twistcli images scan --address $CONSOLE_URL --user=$USER --password=$PASSWORD --details "ap-<< parameters.directory >>:${CIRCLE_SHA1}"
```

2023-09-25 16:09 UTC, danielhoherd commented on .circleci/continue-config.yml
> +            curl -k -u $USER:$PASSWORD --output twistcli $CONSOLE_URL"/api/v1/util/twistcli"
```suggestion
            curl -k -u "$USER:$PASSWORD" --output twistcli "$CONSOLE_URL/api/v1/util/twistcli"
```

2023-09-25 16:10 UTC, danielhoherd commented on .circleci/continue-config.yml.j2
> +            curl -k -u $USER:$PASSWORD --output twistcli $CONSOLE_URL"/api/v1/util/twistcli"
```suggestion
            curl -k -u "$USER:$PASSWORD" --output twistcli "${CONSOLE_URL}/api/v1/util/twistcli"
```

2023-09-25 16:13 UTC, danielhoherd requested changes
This currently does not error when a vulnerability is found. <https://app.circleci.com/pipelines/github/astronomer/ap-vendor/2156/workflows/57485111-9a92-427c-9691-d3df558e3ef0/jobs/43279/parallel-runs/0/steps/0-105> We need this step to fail if a vulnerability is found unless that vulnerability has been ignored.

2023-09-25 16:17 UTC, pgvishnuram commented
I think thats fine daniel since else you will keep ending up on vulnerabilities that we are not responsible for

2023-09-25 18:34 UTC, danielhoherd commented
@pgvishnuram 

> vulnerabilities that we are not responsible for

We are responsible for all vulnerabilities in the software we ship. We can't release software that has a vulnerability that we have not acknowledged and added an exception for.

To put it a different way, the CI security scan serves a specific purpose: alerting a developer like you or me that there is a vulnerability in the image. Not failing on this steps means that we will inevitably release software that has a vulnerability in it that we didn't see.

Not failing in CI is a big step down in security confidence. CC @VictorLuc4

2023-09-26 05:10 UTC, pgvishnuram commented
@danielhoherd Im merging this and later we can tweak it as per the needs since we have a open ticket

2023-09-26 13:28 UTC, danielhoherd commented on bin/twistcli_validator.py
> +ROOT_DIRECTORY = Path(__file__).parent.parent
```suggestion
ROOT_DIRECTORY = [x for x in Path(__file__).resolve().parents if (x / ".git").is_dir()][-1]
```

2023-09-26 13:30 UTC, danielhoherd commented on bin/twistcli_validator.py
> +import json
```suggestion
#!/usr/bin/env python3
import json
```

2023-09-26 13:37 UTC, danielhoherd commented on bin/twistcli_validator.py
> +    output = [vul["id"] for vul in vulnerabilities]
```suggestion
data = json.loads(Path(f"{SCAN_RESULTS_FILE_PATH}/scan-results.json").read_text())
output = [vuln["id"] for vuln in data.get("results", [])[0].get("vulnerabilities", [])]
```

2023-09-26 13:38 UTC, danielhoherd commented on bin/twistcli_validator.py
> +        if ignore_list == output:
This `output` variable name should be more specific. Maybe `cves` would be good.
```suggestion
        if ignore_list == output:
```

2023-09-26 13:43 UTC, danielhoherd commented on bin/twistcli_validator.py
> +            print("New vulnerabilities found.Fix them or add into ignore list")
We should print the CVEs that are not ignored. We can do this with `set`:
```
>>> ignore_list = ['CVE-2023-39320', 'CVE-2023-29405', 'CVE-2023-29404', 'CVE-2023-29402']
>>> cves = ['CVE-2023-39320', 'CVE-2023-29405', 'CVE-2023-29404', 'CVE-2023-29402', 'CVE-2023-29403', 'CVE-2023-39533', 'CVE-2023-39322', 'CVE-2023-39321']
>>> set(cves) - set(ignore_list)
{'CVE-2023-39321', 'CVE-2023-39533', 'CVE-2023-39322', 'CVE-2023-29403'}
```

Or with a comprehension:

```
>>> [cve for cve in cves if cve not in ignore_list]
['CVE-2023-29403', 'CVE-2023-39533', 'CVE-2023-39322', 'CVE-2023-39321']
```

2023-09-26 18:25 UTC, danielhoherd commented on bin/twistcli_validator.py
> +        sys.exit(1)
I refactored this whole script:
```suggestion
#!/usr/bin/env python3
import json
from pathlib import Path
import os


git_root = [x for x in Path(__file__).resolve().parents if (x / ".git").is_dir()][
    -1
]
project_name = os.getenv("PROJECT_DIRECTORY")
scan_results_file_path = f"{git_root}/{project_name}"

data = json.loads(Path(f"{scan_results_file_path}/scan-results.json").read_text())
found_cves = [
    vuln["id"] for vuln in data.get("results", [])[0].get("vulnerabilities", [])
]

def cve_list_to_string(list):
    if list:
        return '\n' + '\n'.join([f'  - {item}' for item in list]) + '\n'
    return 'none\n'

def get_ignored_cves():
    ignore_file = Path(f"{scan_results_file_path}/twistcliignore")
    if ignore_file.is_file():
        return [line.strip() for line in ignore_file.read_text().splitlines()]
    return []

ignored_cve_list = get_ignored_cves()

if found_cves:
    print(f"New vulnerabilities found. Fix them or add them to {project_name}/twistcliignore\n")

    new_cves = [cve for cve in found_cves if cve not in ignored_cve_list]
    print(f"New CVEs that are not found in {project_name}/twistcliignore: {cve_list_to_string(new_cves)}")

    old_cves = [cve for cve in found_cves if cve in ignored_cve_list and cve in found_cves]
    print(f"Old CVEs that exist now but are already in {project_name}/twistcliignore: {cve_list_to_string(old_cves)}")

    solved_cves = [cve for cve in ignored_cve_list if cve not in found_cves]
    print(f"Solved CVEs that can be removed from {project_name}/twistcliignore: {cve_list_to_string(solved_cves)}")

    raise SystemExit(1)
```

The output looks like this:
```
$ bin/twistcli_validator.py
2023-09-26T14:17:53-0400
New vulnerabilities found. Fix them or add them to pgbouncer-exporter/twistcliignore

New CVEs that are not found in pgbouncer-exporter/twistcliignore:
  - CVE-2023-29405
  - CVE-2023-29404
  - CVE-2023-29402

Old CVEs that exist now but are already in pgbouncer-exporter/twistcliignore:
  - CVE-2023-39320

Solved CVEs that can be removed from pgbouncer-exporter/twistcliignore:
  - CVE-5555

```

2023-09-26 18:35 UTC, danielhoherd approved these changes
I think we're good here. We can clean up anything that slipped through the cracks in the next iteration.

2023-09-26 18:37 UTC, merged